---
collectors:
  enabled: textfile

collector:
  textfile:
    directories:
      - "C:\\ProgramData\\Infopercept\\logs"

log:
  level: info  # This captures all levels of logs: error, warn, info, debug, and verbose

scrape:
  timeout-margin: 0.5

telemetry:
  path: /metrics
  max-requests: 5

web:
  listen-address: ":9182"
